// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/marshal/snapshot.proto

package snapshot

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Record struct {
	Expire               *int64   `protobuf:"varint,1,opt,name=Expire" json:"Expire,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,req,name=Key" json:"Key,omitempty"`
	Val                  []byte   `protobuf:"bytes,3,opt,name=Val" json:"Val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1759bde36ae8889, []int{0}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetExpire() int64 {
	if m != nil && m.Expire != nil {
		return *m.Expire
	}
	return 0
}

func (m *Record) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Record) GetVal() []byte {
	if m != nil {
		return m.Val
	}
	return nil
}

type Records struct {
	List                 []*Record `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Records) Reset()         { *m = Records{} }
func (m *Records) String() string { return proto.CompactTextString(m) }
func (*Records) ProtoMessage()    {}
func (*Records) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1759bde36ae8889, []int{1}
}

func (m *Records) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Records.Unmarshal(m, b)
}
func (m *Records) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Records.Marshal(b, m, deterministic)
}
func (m *Records) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Records.Merge(m, src)
}
func (m *Records) XXX_Size() int {
	return xxx_messageInfo_Records.Size(m)
}
func (m *Records) XXX_DiscardUnknown() {
	xxx_messageInfo_Records.DiscardUnknown(m)
}

var xxx_messageInfo_Records proto.InternalMessageInfo

func (m *Records) GetList() []*Record {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*Record)(nil), "Record")
	proto.RegisterType((*Records)(nil), "Records")
}

func init() { proto.RegisterFile("common/marshal/snapshot.proto", fileDescriptor_a1759bde36ae8889) }

var fileDescriptor_a1759bde36ae8889 = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4d, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0xcf, 0x4d, 0x2c, 0x2a, 0xce, 0x48, 0xcc, 0xd1, 0x2f, 0xce, 0x4b, 0x2c, 0x28,
	0xce, 0xc8, 0x2f, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x72, 0xe1, 0x62, 0x0b, 0x4a, 0x4d,
	0xce, 0x2f, 0x4a, 0x11, 0x12, 0xe3, 0x62, 0x73, 0xad, 0x28, 0xc8, 0x2c, 0x4a, 0x95, 0x60, 0x54,
	0x60, 0xd4, 0x60, 0x0e, 0x82, 0xf2, 0x84, 0x04, 0xb8, 0x98, 0xbd, 0x53, 0x2b, 0x25, 0x98, 0x14,
	0x98, 0x34, 0x78, 0x82, 0x40, 0x4c, 0x90, 0x48, 0x58, 0x62, 0x8e, 0x04, 0xb3, 0x02, 0x23, 0x48,
	0x24, 0x2c, 0x31, 0x47, 0x49, 0x8d, 0x8b, 0x1d, 0x62, 0x4a, 0xb1, 0x90, 0x34, 0x17, 0x8b, 0x4f,
	0x66, 0x71, 0x89, 0x04, 0xa3, 0x02, 0xb3, 0x06, 0xb7, 0x11, 0xbb, 0x1e, 0x44, 0x3c, 0x08, 0x2c,
	0xe8, 0xa4, 0x14, 0xa5, 0x80, 0xc3, 0x39, 0xd6, 0x30, 0x06, 0x20, 0x00, 0x00, 0xff, 0xff, 0x58,
	0x06, 0x99, 0x71, 0xb1, 0x00, 0x00, 0x00,
}
