[program:machine-exporter]

directory = /home/homework/prometheus/machine-exporter
command = /home/homework/prometheus/machine-exporter/bin/machine_exporter --conf=/home/homework/prometheus/machine-exporter/conf/machine-exporter.toml

stopsignal = TERM
# 跟随supvisord启动
autostart = true
# 自动重启
autorestart = true
# 启动延时执行1秒
startsecs = 1
# 启动尝试次数
startretries = 5
redirect_stderr = true
#日志输出
stderr_logfile = /home/homework/prometheus/machine-exporter/bin/machine_exporter.err
stdout_logfile = /home/homework/prometheus/machine-exporter/bin/machine_exporter.dump
[supervisord]
logfile = /home/homework/prometheus/machine-exporter/bin/supervisord.log
pidfile = /home/homework/prometheus/machine-exporter/bin/supervisord.pid