
##################################################
#                                                #
#                  Stored-Dashboard              #
#                                                #
##################################################
coordinator_name = "database"
coordinator_addr = "/home/homework/bitalosproxy"
coordinator_auth = ""

# Set Stored Product Name/Auth.
product_name = "{{.TaskExt.ClusterName}}"
product_auth = "{{.TaskExt.StoredAuth}}"

# Set bind address for admin(rpc), tcp only.
admin_addr = "0.0.0.0:{{.TaskExt.ServicePort}}"
admin_model= "raft"
paas_host = "127.0.0.1:1000"
dh_refer = "http://127.0.0.1:1000/"
area = "ch"
env = "demo"
cloud = "{{.TaskExt.CloudType}}"

[database]
username = "stored_paas_app"
password = "eiF_4EQv6XVJYd6"
hostport = "10.98.128.137:3306"
dbname = "stored_paas"

[stored]
txcloud = []
ali = []
baidu = []
txzns = ""
alizns = ""
bdzns = ""