[program:{{.TaskExt.ClusterName}}]
directory = {{.TaskPath}}
command = {{.TaskPath}}/run.sh start-foreground
user = homework
# 跟随supvisord启动
autostart = true
# 自动重启
autorestart = true
# 启动延时执行1秒
startsecs = 1
# 启动尝试次数
startretries = 5
[supervisord]
logfile = {{.TaskPath}}/supervisord-proxy.log
pidfile = {{.TaskPath}}/supervisord-proxy.pid