[program:{{.TaskExt.ClusterName}}]
directory = {{.TaskPath}}
command = {{.TaskPath}}/run.sh start-foreground
user = homework
autostart = true
autorestart = true
startsecs = 1
startretries = 5
[supervisord]
logfile = {{.TaskPath}}/supervisord-proxy.log
pidfile = {{.TaskPath}}/supervisord-proxy.pid