[program:{{.TaskExt.ClusterName}}]

# user
directory = {{.TaskPath}}
command = {{.TaskPath}}/bin/bitalostored --conf.file={{.TaskPath}}/config/config.toml
environment = LD_LIBRARY_PATH="{{.TaskRoot}}/lib/lib-stored",APP_NAME="{{.TaskExt.ClusterName}}",GOGC=300,GIN_MODE="release",MALLOC_CONF="background_thread:true,metadata_thp:auto,dirty_decay_ms:30000,muzzy_decay_ms:30000"

stopsignal = TERM
autostart = true
autorestart = true
startsecs = 1
startretries = 5
redirect_stderr = true
stderr_logfile = {{.TaskPath}}/bitalos-server.dump
stdout_logfile = {{.TaskPath}}/bitalos-server.dump
[supervisord]
logfile = {{.TaskPath}}/supervisord-server.log
pidfile = {{.TaskPath}}/supervisord-server.pid